#!/usr/bin/env sh

branch_name="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch_name" = "master" ]; then
  echo "Direct commits to 'master' are disabled. Create a feature branch and open a PR."
  exit 1
fi

exit 0