-- SmartStudy Subject Content Seed Script
-- Adds syllabus-aligned course content summaries for all catalog subjects

USE SmartStudyDB;

GO

IF OBJECT_ID('tempdb..#CourseContentSeed') IS NOT NULL
  DROP TABLE #CourseContentSeed;

CREATE TABLE #CourseContentSeed (
  SubjectCode NVARCHAR(50) NOT NULL,
  ContentSummary NVARCHAR(MAX) NOT NULL
);

INSERT INTO #CourseContentSeed (SubjectCode, ContentSummary)
VALUES
  ('da101', 'Foundations of communication: listening, speaking, reading, and writing strategies for academic settings; Vocabulary and grammar for technical communication; Structured paragraph and essay writing with coherence and clarity; Oral presentations, group discussions, and argument framing; Critical reading of academic and informational texts; Professional communication for reports, emails, and classroom interaction.'),
  ('da102', 'Spreadsheet based data analysis workflow and reproducible tabular operations; Data ingestion from CSV and mixed sources and data type handling; Data cleaning, deduplication, missing value treatment, and transformation; Descriptive statistics and exploratory summaries for numeric and categorical variables; Pivot tables, lookups, joins, and formula based feature creation; Visualization using charts and dashboards for analytical storytelling; Introductory regression and what-if analysis for decision support.'),
  ('da103', 'Probability spaces, events, counting methods, and conditional probability; Random variables and common discrete and continuous distributions; Expectation, variance, covariance, and correlation measures; Joint, marginal, and conditional distributions with independence concepts; Laws of large numbers and central limit theorem foundations; Sampling distributions and probabilistic reasoning for data science tasks; Applied problem solving using probability models in uncertainty driven systems.'),
  ('da104', 'Program structure in C, compilation model, and execution flow; Data types, operators, expressions, and type conversion rules; Control flow with conditionals, loops, and switch based branching; Functions, scope, storage classes, and modular design practices; Arrays, strings, pointers, dynamic memory, and pointer arithmetic; Structures, unions, and user defined data abstractions; File handling, formatted input output, and defensive error handling patterns.'),
  ('da-105-linear-algebra', 'Systems of linear equations and Gaussian elimination methods; Matrix operations, determinant, inverse, rank, and null space concepts; Vector spaces, basis, dimension, and subspace interpretation; Linear transformations, kernel image, and matrix representation; Eigenvalues, eigenvectors, diagonalization, and spectral intuition; Inner product spaces, orthogonality, projection, and Gram Schmidt process; Positive definite matrices, QR factorization, SVD, and data science applications.'),
  ('da106', 'Overview of Data Science, Data Science task workflow; Data collection and management: Nature of data sets; Multimodal data, structured and unstructured data; Data collection and curation; Concepts in data management: XML and JSON file formats, basics of SQL; Data cleaning, exploration, plots: Reading and exporting data, cleaning data; Exploratory data analysis: Missing values, Outlier detection, Data Transformation; Model building, training, evaluation: Machine Learning task workflow, train/validation/test set preparation, Linear regression and Bayes classifier; Model training and performance analysis; Examples of Data Science applications.'),
  ('da107', 'Computer hardware and architecture fundamentals including CPU memory and I O; Operating system concepts: process management, scheduling, and file systems; Command line usage, shell scripting, and automation of system tasks; User management, permissions, and secure configuration practices; Package management, software installation, and environment setup; Networking basics for host connectivity and troubleshooting; System administration workflows for reliability and maintenance.'),
  ('da108', 'Python syntax, execution model, and interactive development workflow; Primitive data types, strings, lists, tuples, sets, and dictionaries; Control structures including branching, loops, and comprehensions; Functions, arguments, scope rules, recursion, and modularization; Object oriented programming with classes, inheritance, and encapsulation; Exceptions, file operations, and context managers for robust code; Introductory libraries and scripting patterns used in data science projects.'),
  ('da109', 'Introduction to AI problem spaces and intelligent agent formulation; Search strategies including uninformed and informed search methods; Knowledge representation with logic and rule based inference; Planning and reasoning under deterministic and uncertain settings; Probabilistic reasoning basics and graphical intuition; Learning paradigms: supervised, unsupervised, and reinforcement learning overview; Case studies showing AI methods in real world applications.'),
  ('da110', 'Linear and nonlinear data structures for efficient computation; Arrays, linked lists, stacks, and queues with implementation tradeoffs; Trees including BST, AVL, heaps, and traversal techniques; Hashing methods, collision handling, and dictionary abstractions; Graph representations and traversals using BFS and DFS; Sorting and searching algorithms with complexity comparison; Practical use of data structures in analytics and systems code.'),
  ('da111', 'Asymptotic analysis and formal reasoning about algorithm complexity; Divide and conquer strategies and recurrence based analysis; Greedy methods and correctness arguments with counterexample analysis; Dynamic programming state design and optimization patterns; Graph algorithms including shortest paths, spanning trees, and flows; Complexity classes and computational limits in practice; Algorithm engineering for scalable problem solving.'),
  ('da112', 'R language fundamentals and interactive statistical computing workflow; Vectors, matrices, lists, factors, and data frame manipulation; Control flow, apply family functions, and functional style programming; Data import, export, wrangling, and missing value handling; Statistical summaries, hypothesis oriented exploration, and reporting; Visualization using base plotting and tidy style charting patterns; Building reproducible scripts for analytics assignments and projects.'),
  ('da201', 'Relational database design, ER modeling, and schema normalization; Relational algebra concepts and SQL query formulation; Constraints, keys, indexes, and performance aware schema choices; Transactions, ACID properties, and concurrency control mechanisms; Query processing, optimization basics, and physical storage structures; Logging, recovery methods, and failure handling principles; Practical SQL workflows for analytics and application backends.'),
  ('da202', 'Java language fundamentals and platform execution model; Object oriented design with classes, interfaces, inheritance, and polymorphism; Exception handling, collections framework, and generic programming; File I O, streams, and serialization fundamentals; Multithreading, synchronization, and concurrent programming basics; Networking APIs and JDBC based database interactions; Building small end to end Java applications with modular structure.'),
  ('da203', 'Optimization problem formulation for engineering and data science; Convex sets, convex functions, and optimality conditions; Unconstrained optimization with gradient based methods; Newton and quasi Newton techniques with convergence intuition; Linear programming, simplex method, and duality interpretation; Constrained optimization using KKT conditions and penalty style methods; Numerical considerations and practical optimization workflows.'),
  ('da204', 'Econometric modeling foundations for empirical data analysis; Simple and multiple linear regression with interpretation of coefficients; Estimation assumptions and diagnostic checks for model validity; Heteroscedasticity and autocorrelation detection with corrective strategies; Instrumental variable methods for endogeneity problems; Binary response models for categorical outcomes; Applied econometric case analysis for policy and business contexts.'),
  ('da205', 'Data warehouse architecture and dimensional modeling concepts; ETL pipeline design for extraction cleansing and transformation; OLAP style analytics and aggregate query workflows; Frequent itemset and association rule mining concepts; Graph mining principles for connected data structures; Stream mining basics for evolving data environments; End to end data mining process from preprocessing to evaluation.'),
  ('da206', 'Point estimation methods and desirable estimator properties; Maximum likelihood estimation and likelihood based inference; Confidence intervals and hypothesis testing framework; Test statistics, p values, and decision error interpretation; Bayesian foundations with prior posterior updating intuition; Asymptotic behavior and large sample approximations; Statistical inference applications in data driven decision making.'),
  ('da207', 'Signal representation in time and frequency domains; LTI systems, convolution, and impulse response analysis; Fourier series and Fourier transform based reasoning; Sampling theorem and aliasing in digital signal processing; Z transform and discrete time system characterization; Filter concepts and frequency response interpretation; Signal processing applications in communication and analytics systems.'),
  ('da208', 'Social media data acquisition using APIs and crawling pipelines; Text preprocessing, tokenization, and feature extraction methods; Ranking, recommendation, and engagement modeling techniques; Embedding methods and representation learning for short text; Network analysis with graph metrics and community structure; Sentiment and topic analysis for social content streams; Applied social media analytics case studies and ethics considerations.'),
  ('da209', 'Principles of effective data visualization and human perception; Chart selection for comparison distribution relationship and composition; Visual encoding choices, scales, color, and annotation strategy; Interactive visualization concepts for exploratory analytics; Geospatial and temporal visual storytelling patterns; Dashboard composition and communication for decision support; Critiquing and improving visualization quality using real examples.'),
  ('da210', 'Time series components: trend, seasonality, cyclic behavior, and noise; Stationarity concepts and transformations for model readiness; Autocorrelation analysis and model identification workflows; AR, MA, ARMA, and ARIMA models for forecasting; Parameter estimation, diagnostics, and residual analysis; Seasonal and nonstationary model extensions; Forecast evaluation metrics and deployment oriented case studies.'),
  ('da261', 'Supervised learning pipeline from feature design to evaluation; Probabilistic classifiers including Bayesian decision frameworks; Distance based methods such as k nearest neighbors; Decision trees and model interpretability fundamentals; Unsupervised learning with clustering and mixture models; Dimensionality reduction using PCA and discriminant methods; Validation strategies and performance analysis for reliable modeling.'),
  ('da262', 'Recommendation problem formulation and feedback data modeling; Content based filtering and user item profile construction; Collaborative filtering with memory and model based approaches; Matrix factorization techniques for latent preference learning; Context aware and session aware recommendation extensions; Ranking metrics, offline evaluation, and online experimentation basics; Practical concerns: cold start, bias, diversity, and scalability.'),
  ('da301', 'Cloud computing foundations and distributed service architectures; Virtualization, containers, and resource orchestration principles; Service models including IaaS, PaaS, and SaaS usage patterns; Cloud storage systems and data lifecycle management; Security architecture, identity, access control, and compliance basics; Reliability patterns including elasticity, fault tolerance, and monitoring; Applying cloud platforms to machine learning and analytics workloads.'),
  ('da302', 'Neural network foundations and gradient based learning; Backpropagation mechanics and optimization strategies; Regularization, normalization, and generalization techniques; Convolutional neural networks for image understanding tasks; Sequence modeling with RNN, LSTM, and attention mechanisms; Transformer architecture basics and representation learning; Generative modeling concepts and practical deep learning workflows.'),
  ('da326', 'Computer vision pipeline design with deep neural architectures; Advanced CNN structures and transfer learning strategies; Encoder decoder models for segmentation and dense prediction; Vision transformers and hybrid architectural trends; Generative vision models including GAN and VAE variants; Training stabilization, augmentation, and evaluation best practices; Recent research directions and deployment considerations for vision systems.'),
  ('da354', 'Wireless communication foundations and channel behavior modeling; Signal detection and spectrum sensing with intelligent methods; Resource allocation and scheduling under dynamic constraints; Adaptive modulation and coding with learning based control; MIMO and multiuser communication optimization perspectives; AI for network planning, anomaly detection, and traffic prediction; Applications in IoT and next generation wireless systems.'),
  ('da361', 'Financial mathematics foundations and time value of money; Bond pricing, yield analysis, and fixed income risk measures; Equity valuation methods and cash flow based modeling; Portfolio theory, diversification, and efficient frontier analysis; Asset pricing frameworks including CAPM and multifactor ideas; Risk measurement, performance attribution, and benchmarking; Practical investment analytics with data driven decision support.'),
  ('dao3021', 'Efficient deep learning system design across hardware platforms; Model compression with pruning, quantization, and distillation methods; Throughput latency tradeoffs for inference and deployment targets; Memory bandwidth and compute aware architecture optimization; Compiler and runtime considerations for accelerated workloads; Scalable training pipelines for multi device and distributed settings; Performance profiling and optimization case studies.'),
  ('dao3062', 'Digital manufacturing concepts and smart factory data pipelines; Additive manufacturing processes and quality influencing parameters; Sensor based process monitoring and anomaly detection methods; AI driven process optimization and predictive maintenance workflows; Digital twin foundations for manufacturing system simulation; Integration of planning, control, and analytics in production; Industrial case studies on data driven manufacturing transformation.'),
  ('dao3063', 'Leadership theories and practical leadership styles in teams; Emotional intelligence, motivation, and behavior in organizations; Communication frameworks for influence and stakeholder alignment; Conflict resolution, negotiation, and collaborative decision making; Change management principles and transformation leadership; Ethics, accountability, and leadership in uncertain environments; Personal leadership development planning and reflective practice.');

MERGE CourseContents AS target
USING (
  SELECT s.SubjectID, c.ContentSummary
  FROM #CourseContentSeed c
  JOIN Subjects s ON s.SubjectCode = c.SubjectCode
) AS source
ON target.SubjectID = source.SubjectID
WHEN MATCHED THEN
  UPDATE SET
    target.ContentSummary = source.ContentSummary,
    target.UpdatedAt = GETUTCDATE()
WHEN NOT MATCHED BY TARGET THEN
  INSERT (SubjectID, ContentSummary, UpdatedAt)
  VALUES (source.SubjectID, source.ContentSummary, GETUTCDATE());

SELECT 'Course content seed completed successfully!' AS [Status];
SELECT COUNT(*) AS TotalCourseContentRows FROM CourseContents;
SELECT COUNT(*) AS ExpectedSeedSubjects FROM #CourseContentSeed;

IF OBJECT_ID('tempdb..#CourseContentSeed') IS NOT NULL
  DROP TABLE #CourseContentSeed;
